### ISSUE TITLE
입력된 정보로 잔고 계산 기능

### ISSUE THREAD

**Issue by leadbrain** [cashplan/cash-service#6]
입력된 금액의 합계를 보여주는 기능 추가
잔고 관리를 DB에서 어떻게 할지 고민 필요
입력시 수입/지출 구별 하는 기능도 추가

**Comment by cardia** [comment]
수입 / 지출 / 잔고 테이블을 분리 시키는건 어떨까요?

**Comment by leadbrain** [comment]
join의 압박? ㅎㅎ
